# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-10 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('team', '0001_initial'),
        ('shgroup', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Project')),
                ('shGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shgroup.SHGroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('userPermission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Permission')),
            ],
        ),
    ]
