# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_nav', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagenav',
            name='extended_object',
        ),
        migrations.RemoveField(
            model_name='pagenav',
            name='public_extension',
        ),
    ]
