# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('page_nav', '0002_auto_20191012_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenav',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Page'),
            preserve_default=False,
        ),
    ]
