# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_nav', '0003_pagenav_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagenav',
            name='id',
        ),
        migrations.AlterField(
            model_name='pagenav',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.Page'),
        ),
    ]
