# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_nav', '0004_auto_20191012_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagenav',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
