# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_nav', '0005_auto_20191012_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagenav',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='page_order', serialize=False, to='cms.Page'),
        ),
    ]
