# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import page_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSetting',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.Page')),
                ('pageType', enumfields.fields.EnumField(enum=page_setting.models.PageType, max_length=1)),
            ],
        ),
    ]
