# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('page_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_extra_field', models.CharField(max_length=50)),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extended_fields', to='cms.Page', unique=True, verbose_name='Page')),
            ],
        ),
    ]
