# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_setting', '0002_extendedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesetting',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pages', serialize=False, to='cms.Page'),
        ),
    ]
