# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_setting', '0003_auto_20191019_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedpage',
            name='page',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extended_fields', to='cms.Page', verbose_name='Page'),
        ),
    ]
