# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-10 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SHCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapType', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
                ('SHCategoryName', models.CharField(max_length=50)),
                ('SHCategoryDesc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SHGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHGroupName', models.CharField(max_length=255)),
                ('SHGroupAbbrev', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SHGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shgroup.SHGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SHMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipStatus', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.Organization')),
                ('shCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shgroup.SHCategory')),
                ('subjectUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjectUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shcategory',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shgroup.SHGroup'),
        ),
        migrations.AddField(
            model_name='shcategory',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Survey'),
        ),
    ]
