# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0002_aoquestion_pagesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoquestion',
            name='PageSetting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aopagesetting', to='page_setting.PageSetting'),
        ),
    ]
